<?php

namespace ContainerZUU1X2r;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0_VNo13Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0.VNo13' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0.VNo13'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AuthorController::ShowAuth' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\AuthorController::addAuthor' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\AuthorController::deleteAuth' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\AuthorController::listAuth' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\AuthorController::updateAuthor' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\SymfonyConsoleMakeCrudController::delete' => ['privates', '.service_locator.LG7ntvO', 'get_ServiceLocator_LG7ntvOService', true],
            'App\\Controller\\SymfonyConsoleMakeCrudController::edit' => ['privates', '.service_locator.LG7ntvO', 'get_ServiceLocator_LG7ntvOService', true],
            'App\\Controller\\SymfonyConsoleMakeCrudController::index' => ['privates', '.service_locator.E86grY4', 'get_ServiceLocator_E86grY4Service', true],
            'App\\Controller\\SymfonyConsoleMakeCrudController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SymfonyConsoleMakeCrudController::show' => ['privates', '.service_locator.KJSb96P', 'get_ServiceLocator_KJSb96PService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AuthorController:ShowAuth' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\AuthorController:addAuthor' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\AuthorController:deleteAuth' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\AuthorController:listAuth' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\AuthorController:updateAuthor' => ['privates', '.service_locator.o6sN0hZ', 'get_ServiceLocator_O6sN0hZService', true],
            'App\\Controller\\SymfonyConsoleMakeCrudController:delete' => ['privates', '.service_locator.LG7ntvO', 'get_ServiceLocator_LG7ntvOService', true],
            'App\\Controller\\SymfonyConsoleMakeCrudController:edit' => ['privates', '.service_locator.LG7ntvO', 'get_ServiceLocator_LG7ntvOService', true],
            'App\\Controller\\SymfonyConsoleMakeCrudController:index' => ['privates', '.service_locator.E86grY4', 'get_ServiceLocator_E86grY4Service', true],
            'App\\Controller\\SymfonyConsoleMakeCrudController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SymfonyConsoleMakeCrudController:show' => ['privates', '.service_locator.KJSb96P', 'get_ServiceLocator_KJSb96PService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AuthorController::ShowAuth' => '?',
            'App\\Controller\\AuthorController::addAuthor' => '?',
            'App\\Controller\\AuthorController::deleteAuth' => '?',
            'App\\Controller\\AuthorController::listAuth' => '?',
            'App\\Controller\\AuthorController::updateAuthor' => '?',
            'App\\Controller\\SymfonyConsoleMakeCrudController::delete' => '?',
            'App\\Controller\\SymfonyConsoleMakeCrudController::edit' => '?',
            'App\\Controller\\SymfonyConsoleMakeCrudController::index' => '?',
            'App\\Controller\\SymfonyConsoleMakeCrudController::new' => '?',
            'App\\Controller\\SymfonyConsoleMakeCrudController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AuthorController:ShowAuth' => '?',
            'App\\Controller\\AuthorController:addAuthor' => '?',
            'App\\Controller\\AuthorController:deleteAuth' => '?',
            'App\\Controller\\AuthorController:listAuth' => '?',
            'App\\Controller\\AuthorController:updateAuthor' => '?',
            'App\\Controller\\SymfonyConsoleMakeCrudController:delete' => '?',
            'App\\Controller\\SymfonyConsoleMakeCrudController:edit' => '?',
            'App\\Controller\\SymfonyConsoleMakeCrudController:index' => '?',
            'App\\Controller\\SymfonyConsoleMakeCrudController:new' => '?',
            'App\\Controller\\SymfonyConsoleMakeCrudController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
